name: ai_tutor_python
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+10

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  py_engine_desktop: ^1.1.0
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  firebase_auth: ^6.1.1
  multi_split_view: ^3.6.1
  path: ^1.9.1
  path_provider: ^2.1.5
  flutter_code_editor: ^0.3.5
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  flutter_chat_ui: ^2.9.1
  flutter_chat_core: ^2.8.0
  flyer_chat_text_message: ^2.5.1
  flyer_chat_system_message: ^2.1.13
  flyer_chat_text_stream_message: ^2.2.6
  collection: ^1.19.1
  dart_openai:
    git:
      url: https://github.com/yvanvds/openai.git
  envied: ^1.3.1
  loading_animation_widget: ^1.3.0
  google_fonts: ^6.3.2
  shared_preferences: ^2.5.3
  pub_semver: ^2.2.0
  http: ^1.5.0
  crypto: ^3.0.6
  uuid: ^4.5.2
  get_it: ^9.0.5
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  envied_generator: ^1.3.1
  build_runner: ^2.7.1

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - google_fonts/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

  fonts:
    - family: monospace
      fonts:
        - asset: assets/fonts/SVBasicManual.ttf
        - asset: assets/fonts/SVBasicManual-Bold.ttf
          weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package










